### ISSUE TITLE
Deployment Fails with "The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'"

### ISSUE THREAD

**Issue by stasnovogursky** [ITfoxtec/FoxIDs#590] opened 2023-06-27 08:53 UTC
I have been trying to deploy FoxIds for two days and every time there is something new.

When I tried to deploy HEAD of master (tried two times on different subscription) there was "Technical error" during first login. Identical behavior on both deployments
![Screenshot 2023-06-27 094912](https://github.com/ITfoxtec/FoxIDs/assets/46565926/1c56cc08-8c6e-476a-bd2d-ac0565290f09)

Then I tried to deploy 1.0.15 & 1.0.14 versions, but got deployment Failed with this:

![Screenshot 2023-06-27 105230](https://github.com/ITfoxtec/FoxIDs/assets/46565926/f20e1577-8179-444c-9303-e389cadc2c52)

**Comment by Revsgaard** [comment] 2023-06-28 13:18
Thank you for describing the error.
It looks like the /changepassword/ element in the URL is placed incorrectly. 
I'll look in to the error.

**Comment by Revsgaard** [comment] 2023-06-28 19:48
The issue is fixed in version [1.0.17](https://github.com/ITfoxtec/FoxIDs/releases/tag/1.0.17).
The master branch has been updated to version 1.0.17 and you should be able to make a successful deployment. Alternatively, you can [update](https://www.foxids.com/docs/update) your existing deployment (from the master branch) .

**Closed by Revsgaard** 2023-06-28 19:48 UTC

**Comment by VolodymyrPavliukevych** [comment] 2023-06-28 20:02
Dear @Revsgaard, I just deployed version from `1.0.x-development` branch. The issue was fixed.
 Thanks a lot!

**Comment by stasnovogursky** [comment] 2023-06-29 09:19
Extremely appreciate Ur quick response and fix.

Sorry for keeping silence, I am a bit on a travel so I will ask to try once
again by my colleagues.

Thanks & Regards,
Stas
